"""v0.1 initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-13 21:54:23.148081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import retinue.db.types

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("actor_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "job_schedules",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("cron", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_job_schedules")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("run_at", sa.BigInteger(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.BigInteger(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("finished_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_pick", ["status", "run_at", "priority"], unique=False)

    op.create_table(
        "model_policies",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("allow", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_policies")),
    )
    op.create_table(
        "usage_events",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("conversation_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("message_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("total_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.create_index("ix_usage_user_time", ["user_id", "created_at"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("avatar_file_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "agents",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("owner_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "avatar",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column("current_version_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_agents_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("slug", name=op.f("uq_agents_slug")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_table(
        "credentials",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("data_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("data_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("last_verified_at", sa.BigInteger(), nullable=True),
        sa.Column("verify_status", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_credentials_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
    )
    op.create_table(
        "oidc_identities",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oidc_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oidc_identities")),
        sa.UniqueConstraint("provider", "subject", name=op.f("uq_oidc_identities_provider")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("family_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("rotated_to", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("revoked_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_family_id"), ["family_id"], unique=False
        )

    op.create_table(
        "agent_versions",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("agent_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tools",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "mcp_servers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "collection_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "starters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("created_by", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_versions_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint("agent_id", "version", name=op.f("uq_agent_versions_agent_id")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("agent_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("agent_version_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("model_override", sa.Text(), nullable=True),
        sa.Column(
            "params_override",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("forked_from_message_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("folder", sa.Text(), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("is_incognito", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("last_message_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_conversations_agent_id_agents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_conversations_agent_version_id_agent_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index("ix_conv_user_recent", ["user_id", "last_message_at"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("conversation_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("parent_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("agent_version_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column(
            "error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["messages.id"], name=op.f("fk_messages_parent_id_messages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index("ix_msg_conv", ["conversation_id", "created_at"], unique=False)
        batch_op.create_index("ix_msg_parent", ["parent_id"], unique=False)

    op.create_table(
        "message_parts",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("message_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_parts_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_parts")),
        sa.UniqueConstraint("message_id", "idx", name=op.f("uq_message_parts_message_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_parts")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_msg_parent")
        batch_op.drop_index("ix_msg_conv")

    op.drop_table("messages")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index("ix_conv_user_recent")

    op.drop_table("conversations")
    op.drop_table("agent_versions")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_family_id"))

    op.drop_table("refresh_tokens")
    op.drop_table("oidc_identities")
    op.drop_table("credentials")
    op.drop_table("api_keys")
    op.drop_table("agents")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_user_time")

    op.drop_table("usage_events")
    op.drop_table("model_policies")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_pick")

    op.drop_table("jobs")
    op.drop_table("job_schedules")
    op.drop_table("audit_log")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
