"""v0_2_to_v0_6_feature_tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-14 19:03:07.576331

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import retinue.db.types

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# -- FTS5 layer (§13; SQLite only — Postgres search uses ILIKE fallback until
# the tsvector tier lands). External-content tables keyed by the content
# table's rowid, kept in sync by triggers, backfilled on upgrade.

_FTS_TOKENIZE = "tokenize = 'porter unicode61 remove_diacritics 2'"

_FTS_TABLES: list[tuple[str, str, str]] = [
    # (fts_name, content_table, indexed_column)
    ("part_fts", "message_parts", "text_content"),
    ("conv_fts", "conversations", "title"),
    ("filetext_fts", "file_texts", "text"),
    ("chunk_fts", "chunks", "text"),
]


def _fts_upgrade() -> None:
    for fts, table, col in _FTS_TABLES:
        op.execute(
            f"CREATE VIRTUAL TABLE IF NOT EXISTS {fts} USING fts5("
            f"{col}, content='{table}', content_rowid='rowid', "
            f"prefix='2 3', {_FTS_TOKENIZE})"
        )
        op.execute(
            f"CREATE TRIGGER IF NOT EXISTS {fts}_ai AFTER INSERT ON {table} BEGIN "
            f"INSERT INTO {fts}(rowid, {col}) VALUES (new.rowid, coalesce(new.{col}, '')); END"
        )
        op.execute(
            f"CREATE TRIGGER IF NOT EXISTS {fts}_ad AFTER DELETE ON {table} BEGIN "
            f"INSERT INTO {fts}({fts}, rowid, {col}) "
            f"VALUES ('delete', old.rowid, coalesce(old.{col}, '')); END"
        )
        op.execute(
            f"CREATE TRIGGER IF NOT EXISTS {fts}_au AFTER UPDATE OF {col} ON {table} BEGIN "
            f"INSERT INTO {fts}({fts}, rowid, {col}) "
            f"VALUES ('delete', old.rowid, coalesce(old.{col}, '')); "
            f"INSERT INTO {fts}(rowid, {col}) VALUES (new.rowid, coalesce(new.{col}, '')); END"
        )
        op.execute(
            f"INSERT INTO {fts}(rowid, {col}) SELECT rowid, coalesce({col}, '') FROM {table}"
        )


def _fts_downgrade() -> None:
    for fts, table, _col in _FTS_TABLES:
        for suffix in ("ai", "ad", "au"):
            op.execute(f"DROP TRIGGER IF EXISTS {fts}_{suffix}")
        op.execute(f"DROP TABLE IF EXISTS {fts}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blobs",
        sa.Column("blake3", sa.Text(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("storage_backend", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("refcount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("blake3", name=op.f("pk_blobs")),
    )
    op.create_table(
        "embed_cache",
        sa.Column("blake3", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("blake3", "model", name=op.f("pk_embed_cache")),
    )
    op.create_table(
        "collections",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("owner_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embed_model", sa.Text(), nullable=False),
        sa.Column("embed_dim", sa.Integer(), nullable=False),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_collections_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    op.create_table(
        "files",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("owner_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("blake3", sa.Text(), nullable=True),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("mime", sa.Text(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["blake3"], ["blobs.blake3"], name=op.f("fk_files_blake3_blobs")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_files_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index("ix_files_owner_recent", ["owner_id", "created_at"], unique=False)

    op.create_table(
        "mcp_servers",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("owner_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("transport", sa.Text(), nullable=False),
        sa.Column(
            "spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("secret_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "last_status",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_mcp_servers_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_servers")),
    )
    op.create_table(
        "memories",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("user_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_conversation_id", retinue.db.types.UUIDBlob(length=16), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_table(
        "openapi_actions",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("owner_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("auth_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("auth_nonce", sa.LargeBinary(), nullable=True),
        sa.Column(
            "host_allowlist",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_openapi_actions_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_openapi_actions")),
    )
    op.create_table(
        "chunks",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("collection_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("file_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "loc",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_chunks_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_chunks_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index("ix_chunks_coll_file", ["collection_id", "file_id"], unique=False)

    op.create_table(
        "collection_files",
        sa.Column("collection_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("file_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_files_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_collection_files_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("collection_id", "file_id", name=op.f("pk_collection_files")),
    )
    op.create_table(
        "file_texts",
        sa.Column("file_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("extracted_at", sa.BigInteger(), nullable=False),
        sa.Column("extractor", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_texts_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("file_id", name=op.f("pk_file_texts")),
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("file_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("received_bytes", sa.BigInteger(), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("s3_upload_id", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_upload_sessions_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_sessions")),
    )
    op.create_table(
        "shares",
        sa.Column("id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("conversation_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_shares_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shares")),
        sa.UniqueConstraint("token", name=op.f("uq_shares_token")),
    )
    op.create_table(
        "attachments",
        sa.Column("message_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("file_id", retinue.db.types.UUIDBlob(length=16), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_attachments_file_id_files")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_attachments_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", "file_id", name=op.f("pk_attachments")),
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "sqlite":
        _fts_upgrade()


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        _fts_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attachments")
    op.drop_table("shares")
    op.drop_table("upload_sessions")
    op.drop_table("file_texts")
    op.drop_table("collection_files")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_chunks_coll_file")

    op.drop_table("chunks")
    op.drop_table("openapi_actions")
    op.drop_table("memories")
    op.drop_table("mcp_servers")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index("ix_files_owner_recent")

    op.drop_table("files")
    op.drop_table("collections")
    op.drop_table("embed_cache")
    op.drop_table("blobs")
    # ### end Alembic commands ###
